services:
  - type: web
    name: weather-app-backend
    env: docker
    region: singapore # Choose the region closest to your users
    plan: free # or choose a paid plan if needed
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: WEATHER_API_KEY
        sync: false # This will be set manually in Render dashboard
      - key: WEATHER_BASE_URL
        value: https://api.openweathermap.org/data/2.5
    autoDeploy: true
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: redirect
        source: http://*
        destination: https://*
        status: 301 