version: '3.8'

services:
  weather-backend:
    build: .
    image: weather-app-backend
    container_name: weather-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - WEATHER_BASE_URL=https://api.openweathermap.org/data/2.5
    volumes:
      - ./:/app
      - /app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true 